import { Routes } from '@angular/router';
import { Login } from './auth/login/login';
import { HrDashboard } from './hr-dashboard/hr-dashboard';
import { ManagerDashboard } from './manager-dashboard/manager-dashboard';
import { EmployeeDashboard } from './employee-dashboard/employee-dashboard';
import { ReviewPeriod } from './review-period/review-period';
import { ScoreCards } from './score-cards/score-cards';
import { ScoreCardDetails } from './score-card-details/score-card-details';
import { EvaluationComponent } from './evaluation/evaluation';
import { EvaluationDetailsComponent } from './evaluation-details/evaluation-details';
import { EmployeeScoreCardsComponent } from './employee-score-cards/employee-score-cards';
import { EmployeeMyProfileComponent } from './employee-my-profile/employee-my-profile';
import { EmployeeScoreCardDetailsComponent } from './employee-score-card-details/employee-score-card-details';
import { EmployeeSelfEvaluationComponent } from './employee-self-evaluation/employee-self-evaluation';
import { EmployeeSelfEvaluationDetailsComponent } from './employee-self-evaluation-details/employee-self-evaluation-details';
import { EmployeeRatingsComponent } from './employee-ratings/employee-ratings';
import { EmployeeRatingsDetailsComponent } from './employee-ratings-details/employee-ratings-details';
import { ManagerScoreCardsComponent } from './manager-score-cards/manager-score-cards';
import { ManagerScoreCardDetailsComponent } from './manager-score-card-details/manager-score-card-details';
import { ManagerEvaluationComponent } from './manager-evaluation/manager-evaluation';
import { ManagerEvaluationDetailsComponent } from './manager-evaluation-details/manager-evaluation-details';
import { ManagerEvaluationPeriodsComponent } from './manager-evaluation-periods/manager-evaluation-periods';
import { EvaluationPeriodsComponent } from './evaluation-periods/evaluation-periods';
import { PlanningComponent } from './planning/planning';
import { PlanningEmployeesComponent } from './planning-employees/planning-employees';
import { PlanningEmployeeDetailComponent } from './planning-employee-detail/planning-employee-detail';
import { ScoreCardsListComponent } from './score-cards-list/score-cards-list';
import { ScoreCardEmployeeDetailComponent } from './score-card-employee-detail/score-card-employee-detail';
import { ManagerScoreCardsListComponent } from './manager-score-cards-list/manager-score-cards-list';
import { ManagerScoreCardEmployeeDetailComponent } from './manager-score-card-employee-detail/manager-score-card-employee-detail';

export const routes: Routes = [
  { path: '', redirectTo: '/login', pathMatch: 'full' },
  { path: 'login', component: Login },
  { path: 'hr-dashboard', component: HrDashboard },
  { path: 'review-period', component: ReviewPeriod },
  { path: 'planning', component: PlanningComponent },
  { path: 'planning/employees', component: PlanningEmployeesComponent },
  { path: 'planning/employee-detail/:id', component: PlanningEmployeeDetailComponent },
  { path: 'score-cards', component: ScoreCards },
  { path: 'score-cards/list', component: ScoreCardsListComponent },
  { path: 'score-cards/employee-detail/:id', component: ScoreCardEmployeeDetailComponent },
  { path: 'score-card-details', component: ScoreCardDetails },
  { path: 'evaluation-periods', component: EvaluationPeriodsComponent },
  { path: 'evaluation', component: EvaluationComponent },
  { path: 'evaluation-details', component: EvaluationDetailsComponent },
  { path: 'manager-dashboard', component: ManagerDashboard },
  { path: 'manager-score-cards', component: ManagerScoreCardsComponent },
  { path: 'manager-score-cards/list', component: ManagerScoreCardsListComponent },
  { path: 'manager-score-cards/employee-detail/:id', component: ManagerScoreCardEmployeeDetailComponent },
  { path: 'manager-score-card-details', component: ManagerScoreCardDetailsComponent },
  { path: 'manager-evaluation-periods', component: ManagerEvaluationPeriodsComponent },
  { path: 'manager-evaluation', component: ManagerEvaluationComponent },
  { path: 'manager-evaluation-details', component: ManagerEvaluationDetailsComponent },
  { path: 'employee-dashboard', component: EmployeeDashboard },
  { path: 'employee-score-cards', component: EmployeeScoreCardsComponent },
  { path: 'employee-my-profile', component: EmployeeMyProfileComponent },
  { path: 'employee-score-card-details', component: EmployeeScoreCardDetailsComponent },
  { path: 'employee-self-evaluation', component: EmployeeSelfEvaluationComponent },
  { path: 'employee-self-evaluation-details', component: EmployeeSelfEvaluationDetailsComponent },
  { path: 'employee-ratings', component: EmployeeRatingsComponent },
  { path: 'employee-ratings-details', component: EmployeeRatingsDetailsComponent },
  { path: '**', redirectTo: '/login' }
];

