"""Add score card comments

Revision ID: 0a051d7becdf
Revises: 3f846952152c
Create Date: 2025-11-23 21:07:10.230224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a051d7becdf'
down_revision = '3f846952152c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('score_card_comments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('score_card_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('comment_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['score_card_id'], ['score_cards.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('competencies_library', schema=None) as batch_op:
        batch_op.drop_index('idx_competencies_library_category')
        batch_op.drop_index('idx_competencies_library_deleted_at')
        batch_op.drop_index('idx_competencies_library_is_active')
        batch_op.drop_index('idx_competencies_library_org_id')

    with op.batch_alter_table('goals_library', schema=None) as batch_op:
        batch_op.drop_index('idx_goals_library_category')
        batch_op.drop_index('idx_goals_library_deleted_at')
        batch_op.drop_index('idx_goals_library_is_active')
        batch_op.drop_index('idx_goals_library_org_id')

    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_index('idx_organizations_code')
        batch_op.drop_index('idx_organizations_deleted_at')
        batch_op.drop_index('idx_organizations_is_active')

    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.drop_index('idx_permissions_category')
        batch_op.drop_index('idx_permissions_code')
        batch_op.drop_index('idx_permissions_deleted_at')
        batch_op.drop_index('idx_permissions_is_active')

    with op.batch_alter_table('role_permissions', schema=None) as batch_op:
        batch_op.drop_index('idx_role_permissions_permission_id')
        batch_op.drop_index('idx_role_permissions_role_id')

    with op.batch_alter_table('values_library', schema=None) as batch_op:
        batch_op.drop_index('idx_values_library_category')
        batch_op.drop_index('idx_values_library_deleted_at')
        batch_op.drop_index('idx_values_library_is_active')
        batch_op.drop_index('idx_values_library_org_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('values_library', schema=None) as batch_op:
        batch_op.create_index('idx_values_library_org_id', ['org_id'], unique=False)
        batch_op.create_index('idx_values_library_is_active', ['is_active'], unique=False)
        batch_op.create_index('idx_values_library_deleted_at', ['deleted_at'], unique=False)
        batch_op.create_index('idx_values_library_category', ['category'], unique=False)

    with op.batch_alter_table('role_permissions', schema=None) as batch_op:
        batch_op.create_index('idx_role_permissions_role_id', ['role_id'], unique=False)
        batch_op.create_index('idx_role_permissions_permission_id', ['permission_id'], unique=False)

    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.create_index('idx_permissions_is_active', ['is_active'], unique=False)
        batch_op.create_index('idx_permissions_deleted_at', ['deleted_at'], unique=False)
        batch_op.create_index('idx_permissions_code', ['code'], unique=False)
        batch_op.create_index('idx_permissions_category', ['category'], unique=False)

    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.create_index('idx_organizations_is_active', ['is_active'], unique=False)
        batch_op.create_index('idx_organizations_deleted_at', ['deleted_at'], unique=False)
        batch_op.create_index('idx_organizations_code', ['code'], unique=False)

    with op.batch_alter_table('goals_library', schema=None) as batch_op:
        batch_op.create_index('idx_goals_library_org_id', ['org_id'], unique=False)
        batch_op.create_index('idx_goals_library_is_active', ['is_active'], unique=False)
        batch_op.create_index('idx_goals_library_deleted_at', ['deleted_at'], unique=False)
        batch_op.create_index('idx_goals_library_category', ['category'], unique=False)

    with op.batch_alter_table('competencies_library', schema=None) as batch_op:
        batch_op.create_index('idx_competencies_library_org_id', ['org_id'], unique=False)
        batch_op.create_index('idx_competencies_library_is_active', ['is_active'], unique=False)
        batch_op.create_index('idx_competencies_library_deleted_at', ['deleted_at'], unique=False)
        batch_op.create_index('idx_competencies_library_category', ['category'], unique=False)

    op.drop_table('score_card_comments')
    # ### end Alembic commands ###
