"""Add score card competencies and values

Revision ID: 0c3c633a916b
Revises: 0a051d7becdf
Create Date: 2025-11-23 21:08:40.933608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c3c633a916b'
down_revision = '0a051d7becdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('score_card_competencies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('score_card_id', sa.Integer(), nullable=False),
    sa.Column('library_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('target_level', sa.String(length=50), nullable=True),
    sa.Column('added_by_role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['library_id'], ['competencies_library.id'], ),
    sa.ForeignKeyConstraint(['score_card_id'], ['score_cards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('score_card_values',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('score_card_id', sa.Integer(), nullable=False),
    sa.Column('library_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('added_by_role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['library_id'], ['values_library.id'], ),
    sa.ForeignKeyConstraint(['score_card_id'], ['score_cards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('score_card_values')
    op.drop_table('score_card_competencies')
    # ### end Alembic commands ###
