"""add goals planning fields and score card weightage

Revision ID: 26a63d8e7e34
Revises: ec65daf833bf
Create Date: 2025-11-19 22:10:53.478163

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '26a63d8e7e34'
down_revision = 'ec65daf833bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('score_card_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('goal_name', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('success_criteria', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('weight', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('added_by_role', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('added_by_user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('deadline_date', sa.Date(), nullable=True))
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               nullable=True)
        batch_op.alter_column('start_date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('end_date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.drop_constraint('goals_owner_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'score_cards', ['score_card_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['added_by_user_id'], ['id'])
        batch_op.drop_column('title')
        batch_op.drop_column('owner_id')
        batch_op.drop_column('metrics')

    with op.batch_alter_table('score_cards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('goals_weightage', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('competencies_weightage', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('values_weightage', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('score_cards', schema=None) as batch_op:
        batch_op.drop_column('values_weightage')
        batch_op.drop_column('competencies_weightage')
        batch_op.drop_column('goals_weightage')

    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('metrics', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('title', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('goals_owner_id_fkey', 'users', ['owner_id'], ['id'])
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('end_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('start_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               nullable=False)
        batch_op.drop_column('deadline_date')
        batch_op.drop_column('added_by_user_id')
        batch_op.drop_column('added_by_role')
        batch_op.drop_column('weight')
        batch_op.drop_column('success_criteria')
        batch_op.drop_column('goal_name')
        batch_op.drop_column('score_card_id')

    # ### end Alembic commands ###
