"""Add status field to review_periods table

Revision ID: 57cacb67b56c
Revises: 15c5cf36c947
Create Date: 2025-11-18 23:50:30.953365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57cacb67b56c'
down_revision = '15c5cf36c947'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('proficiency_levels', sa.ARRAY(sa.String(length=50)), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('goals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('master',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('value', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('performance_documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('published_date', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('approval_history', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evaluations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('evaluation_type', sa.String(length=20), nullable=False),
    sa.Column('performance_document_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('evaluator_id', sa.Integer(), nullable=True),
    sa.Column('ratings', sa.JSON(), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['evaluator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['performance_document_id'], ['performance_documents.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_index('idx_departments_deleted_at')
        batch_op.drop_index('idx_departments_head_of_department_id')

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_index('idx_employees_deleted_at')
        batch_op.drop_index('idx_employees_department_id')
        batch_op.drop_index('idx_employees_employment_status')
        batch_op.drop_index('idx_employees_is_active')
        batch_op.drop_index('idx_employees_position_id')
        batch_op.drop_index('idx_employees_reporting_manager_id')

    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.drop_index('idx_positions_deleted_at')
        batch_op.drop_index('idx_positions_department_id')

    with op.batch_alter_table('review_periods', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.drop_index('idx_review_periods_deleted_at')
        batch_op.drop_index('idx_review_periods_end_date')
        batch_op.drop_index('idx_review_periods_is_active')
        batch_op.drop_index('idx_review_periods_period_type')
        batch_op.drop_index('idx_review_periods_start_date')

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index('idx_roles_deleted_at')
        batch_op.drop_index('idx_roles_is_active')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('idx_users_deleted_at')
        batch_op.drop_index('idx_users_employee_id')
        batch_op.drop_index('idx_users_is_active')
        batch_op.drop_index('idx_users_role_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('idx_users_role_id', ['role_id'], unique=False)
        batch_op.create_index('idx_users_is_active', ['is_active'], unique=False)
        batch_op.create_index('idx_users_employee_id', ['employee_id'], unique=False)
        batch_op.create_index('idx_users_deleted_at', ['deleted_at'], unique=False)

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_index('idx_roles_is_active', ['is_active'], unique=False)
        batch_op.create_index('idx_roles_deleted_at', ['deleted_at'], unique=False)

    with op.batch_alter_table('review_periods', schema=None) as batch_op:
        batch_op.create_index('idx_review_periods_start_date', ['start_date'], unique=False)
        batch_op.create_index('idx_review_periods_period_type', ['period_type'], unique=False)
        batch_op.create_index('idx_review_periods_is_active', ['is_active'], unique=False)
        batch_op.create_index('idx_review_periods_end_date', ['end_date'], unique=False)
        batch_op.create_index('idx_review_periods_deleted_at', ['deleted_at'], unique=False)
        batch_op.drop_column('status')

    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.create_index('idx_positions_department_id', ['department_id'], unique=False)
        batch_op.create_index('idx_positions_deleted_at', ['deleted_at'], unique=False)

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.create_index('idx_employees_reporting_manager_id', ['reporting_manager_id'], unique=False)
        batch_op.create_index('idx_employees_position_id', ['position_id'], unique=False)
        batch_op.create_index('idx_employees_is_active', ['is_active'], unique=False)
        batch_op.create_index('idx_employees_employment_status', ['employment_status'], unique=False)
        batch_op.create_index('idx_employees_department_id', ['department_id'], unique=False)
        batch_op.create_index('idx_employees_deleted_at', ['deleted_at'], unique=False)

    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.create_index('idx_departments_head_of_department_id', ['head_of_department_id'], unique=False)
        batch_op.create_index('idx_departments_deleted_at', ['deleted_at'], unique=False)

    op.drop_table('evaluations')
    op.drop_table('performance_documents')
    op.drop_table('notifications')
    op.drop_table('master')
    op.drop_table('goals')
    op.drop_table('competencies')
    # ### end Alembic commands ###
